[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "demar"
dependencies = [
    "httpx",
    "psycopg",
    "python-debian",
    "pyyaml",
]

[tool.isort]
profile = 'black'

[tool.black]
line-length = 120
target-version = ['py311']
