#!/bin/bash
cd ~/usrmerge-work
exec \
    ~/demar/massrebuild.py \
    ~/usrmerge-work/sources-unmerged \
    job-unmoved-rebuild \
    --extra-changes ~/Debian/usrmerge/systemd_255-1+XXXXXLOCAL_amd64.changes
